### ISSUE TITLE
add to packagist so i can use travis ci for my custom block

### ISSUE THREAD

**Issue by bnomei** [getkirby/editor#95] opened 2019-08-28 15:00 UTC
currently i have to manually download the plugin to my test directory.

if you add the editor to packagist i could add it to my plugins dev requirements. this way i could write tests for my custom block which is extending your blocks class. only this way it will work with travis ci.

**Comment by bastianallgeier** [comment] 2019-09-02 13:13
This is a duplicate of: https://github.com/getkirby/editor/issues/58

**Closed as completed by bastianallgeier** 2019-09-02 13:13 UTC

**Comment by bnomei** [comment] 2019-09-02 13:22
indeed but i explain why i need it. :D
