### ISSUE TITLE
Ability select pages not just URLs for link field

### ISSUE THREAD

**Issue by alkachur** [getkirby/editor#212] opened 2020-02-26 11:33 UTC
For SEO most useful function in Wordpress is ability to quickly add links to pages that already created when you work with content. Right now in Kirby you need manually add full URL to make an internal connection. It would be a great option for Kirby to have the same functionality.

**Comment by bastianallgeier** [comment] 2020-03-03 10:37
This is a duplicate of #92

**Closed as completed by bastianallgeier** 2020-03-03 10:37 UTC
