### ISSUE TITLE
Clicking on the "Add a caption" text doesn't work

### ISSUE THREAD

**Issue by luxuryluke** [getkirby/editor#151] opened 2019-11-05 19:10 UTC
Problem: Clicking on the "Add a caption" text underneath an image/video that has no caption does not work.

I've tried adding captions to images that have none, but when I do the page scrolls to the top and focuses on a multiselect field that I have on my page (from the blueprint).

**Comment by bastianallgeier** [comment] 2019-11-05 20:02
I know you are a Safari user, but which Safari version do you use and on which OS? I can't reproduce this at all. "Add a caption …" is an input. Clicking it should focus it immediately.

**Comment by luxuryluke** [comment] 2019-11-05 20:06
It had a few issues, but I've now removed Editor and can't get back to testing this until later. :(
It worked in some cases, but I didn't test it enough to see whether it saved it to the image or only kept it in the Editor data(JSON?).
MacOS 10.14.6
Safari Desktop 13.0.3
(This project started life via a starterkit from a few dot versions back)

**Comment by bastianallgeier** [comment] 2019-11-05 20:08
Hm, I wonder if it has any conflicts with other plugins. Would you be able to check in another browser? No rush though.

**Comment by luxuryluke** [comment] 2019-11-05 20:11
That's an interesting point. Updated the core without checking whether the plugins will break is a big issue. I will do that.
Current plugins:

kirby-color-master
kirby-markdown-field-master
kirby-colorextractor-master
gallery
kirby3-xmlsitemap-master

**Comment by bastianallgeier** [comment] 2019-11-19 16:28
I'm really sorry, but I tried in multiple browsers and I cannot reproduce it. I'm pretty sure it's not directly editor related. I'll close this and watch out for more issue reports.

**Closed as completed by bastianallgeier** 2019-11-19 16:28 UTC
Labels: missing: information ❓
